### ISSUE TITLE
Spanner Autoscaler Operator fails guess AuthType fails to guess authentication config

### ISSUE THREAD

**Issue by NurlashKO** [mercari/spanner-autoscaler#91]
## What happened

I have a `SpannerAutoscaler` resource below:

```
apiVersion: spanner.mercari.com/v1beta1
kind: SpannerAutoscaler
metadata:
  labels:
    app: spanner-autoscaler
    version: main
  name: xxx
  namespace: xxx
spec:
  authentication:
    impersonateConfig:
      targetServiceAccount: "spanner-autoscaler@xxx.iam.gserviceaccount.com"
  scaleConfig:
    processingUnits:
      max: 1000
      min: 100
    scaledownStepSize: 2000
    targetCPUUtilization:
      highPriority: 60
  targetInstance:
    instanceId: xxx
    projectId: xxx
```

Error: 
```
... -dev/spanner-autoscaler","error":"rpc error: code = PermissionDenied desc = Caller is missing IAM permission spanner.instances.get on resource projects/xxx/instances/xxx.","stacktrace":"github.com/mercari/spanner-autoscaler/internal/syncer.(*syncer).Start\n\t/workspace/internal/syncer/syncer.go:209"} ...
```
## What you expected to happen
Spanner Autoscaler Operator should be able to impersonate provided service account and fetch metrics from GCP.

# How to fix
Add `type: impersonation` to `.spec.authentication` :

```
apiVersion: spanner.mercari.com/v1beta1
kind: SpannerAutoscaler
metadata:
  labels:
    app: spanner-autoscaler
    version: main
  name: xxx
  namespace: xxx
spec:
  authentication:
    impersonateConfig:
      targetServiceAccount: "spanner-autoscaler@xxx.iam.gserviceaccount.com"
    type: impersonation
  scaleConfig:
    processingUnits:
      max: 1000
      min: 100
    scaledownStepSize: 2000
    targetCPUUtilization:
      highPriority: 60
  targetInstance:
    instanceId: xxx
    projectId: xxx
```

## Environment

Fails in both:
- `mercari/spanner-autoscaler:v0.4.0`
- `mercari/spanner-autoscaler:v0.4.1`
